sonar.projectKey=saleor-dashboard
sonar.projectName=saleor-dashboard
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,**/node_modules/**,**/dist/**,**/build/**

# Cobertura de JS/TS (Jest produce lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# (Opcional) Si usas jest-junit
sonar.junit.reportPaths=junit.xml
